### ISSUE TITLE
Plan and implement what closes a session and starts the algorithm

### ISSUE THREAD

**Issue by frostyshadows** [ubclaunchpad/driver#81]
Should the session close when as soon as one person in the session hits Go or until everyone in the session does? Once it closes, figure out which phone runs the algorithm (probably whichever phone closes the session)

**Comment by grig-guz** [comment]
Letting the algorithm run if one person hits Go may allow some users to abuse this button.
Starting the algorithm when every person hits Go may also be not feasible since one of the passengers may pass out or simply forget to click Go.
Thus, I believe that the most effective solution is running the algorithm only if all DRIVERS hit go. Drivers should be the soberest members of the trip, so it's better to rely on them. Also, I don't think the session should be stopped once the algorithm is finished since the algorithm is merely a suggestion of an optimal route for each driver and passengers. Drivers should be able to assign passengers they want to their cars.
